name: tests

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        poetry-version: [1.1.2]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install packages
        run: |
          # poetry update  # sync lock file
          # poetry lock --no-update  # sync lock file
          # poetry install  # --no-dev
          pip install -r requirements.txt
          pip install flake8 pytest pytest-asyncio
      - name: Run flake8
        run: |
          # poetry run flake8 --exit-zero
          # poetry run pytest
          flake8 --exit-zero
      - name: Run pytest
        run: |
          # poetry run pytest
          pytest tests